var R=require("../../chunks/ssr/[turbopack]_runtime.js")("server/app/_not-found/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__b2589bdc._.js")
R.c("server/chunks/ssr/_334faff3._.js")
R.c("server/chunks/ssr/node_modules_next_dist_esm_build_templates_app-page_355ffff5.js")
R.c("server/chunks/ssr/[root-of-the-server]__4fbe1c60._.js")
R.c("server/chunks/ssr/[root-of-the-server]__6b057281._.js")
R.c("server/chunks/ssr/node_modules_next_dist_70ed294b._.js")
R.c("server/chunks/ssr/apps_main_src_app_cf525cad._.js")
R.c("server/chunks/ssr/[root-of-the-server]__e187d01c._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_9774470f._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_forbidden_45780354.js")
R.c("server/chunks/ssr/apps_main__next-internal_server_app__not-found_page_actions_cf9c8491.js")
R.m(80796)
module.exports=R.m(80796).exports
