var R=require("../../chunks/ssr/[turbopack]_runtime.js")("server/app/_global-error/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__b9356576._.js")
R.c("server/chunks/ssr/_334faff3._.js")
R.c("server/chunks/ssr/node_modules_next_dist_ca7d48ac._.js")
R.c("server/chunks/ssr/[root-of-the-server]__4fbe1c60._.js")
R.c("server/chunks/ssr/[root-of-the-server]__6b057281._.js")
R.c("server/chunks/ssr/node_modules_next_dist_70ed294b._.js")
R.c("server/chunks/ssr/apps_main_src_app_cf525cad._.js")
R.c("server/chunks/ssr/apps_main__next-internal_server_app__global-error_page_actions_0c6c010c.js")
R.m(4389)
module.exports=R.m(4389).exports
