var R=require("../chunks/ssr/[turbopack]_runtime.js")("server/app/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__973597c6._.js")
R.c("server/chunks/ssr/_334faff3._.js")
R.c("server/chunks/ssr/_cd251b1d._.js")
R.c("server/chunks/ssr/[root-of-the-server]__97276f91._.js")
R.c("server/chunks/ssr/[root-of-the-server]__6b057281._.js")
R.c("server/chunks/ssr/node_modules_next_dist_70ed294b._.js")
R.c("server/chunks/ssr/apps_main_src_app_cf525cad._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_global-error_ece394eb.js")
R.c("server/chunks/ssr/apps_main_src_app_layout_tsx_21126575._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_9774470f._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_forbidden_45780354.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_unauthorized_15817684.js")
R.c("server/chunks/ssr/apps_main__next-internal_server_app_page_actions_9cf993f2.js")
R.m(21598)
module.exports=R.m(21598).exports
